/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // VeriBhoomi Standard Government Palette
        gov: {
          navy: "#0A2540",
          navyDark: "#061A2E",
          blue: "#1E40AF",
          blueLight: "#2563EB",
          blueSurface: "#EFF6FF",
          saffron: "#EA580C",
          saffronLight: "#FFF7ED",
          saffronBorder: "#FDBA74",
          emerald: "#15803D",
          emeraldLight: "#F0FDF4",
          amber: "#B45309",
          amberLight: "#FFFBEB",
          red: "#B91C1C",
          redLight: "#FEF2F2",
          slate: "#0F172A",
          muted: "#475569",
          surface: "#F8FAFC",
          card: "#FFFFFF",
          border: "#CBD5E1",
          borderLight: "#E2E8F0"
        },
        // Sovereign Portal Theme Palette (MahaLand / DILRMP Theme)
        surface: "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "surface-variant": "#dae2fd",
        primary: "#000f22",
        "primary-container": "#0a2540",
        "primary-fixed": "#d2e4ff",
        "primary-fixed-dim": "#b0c8eb",
        "on-primary": "#ffffff",
        "on-primary-container": "#768dad",
        "on-primary-fixed": "#001c37",
        "on-primary-fixed-variant": "#314865",
        "inverse-primary": "#b0c8eb",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        secondary: "#0051d5",
        "secondary-container": "#316bf3",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",
        tertiary: "#001209",
        "tertiary-container": "#002a1b",
        "tertiary-fixed": "#85f8c4",
        "tertiary-fixed-dim": "#68dba9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#1a9e70",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137",
        "on-surface": "#131b2e",
        "on-surface-variant": "#43474d",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a"
      },
      spacing: {
        "space-xxs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "margin": "2rem"
      },
      fontFamily: {
        sans: ['"Noto Sans Devanagari"', '"Noto Sans"', 'Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      boxShadow: {
        gov: '0 1px 3px 0 rgba(0, 0, 0, 0.08), 0 1px 2px -1px rgba(0, 0, 0, 0.08)',
        govCard: '0 1px 4px 0 rgba(15, 23, 42, 0.06)',
        govModal: '0 10px 25px -5px rgba(15, 23, 42, 0.15), 0 8px 10px -6px rgba(15, 23, 42, 0.1)'
      }
    },
  },
  plugins: [],
}
